### PR TITLE
Faster looping of sample_locate

### PR DESCRIPTION
**Pull request by ndg63276**
This seems much faster.

### CODE REVIEW

**Comment by ndg63276** [comment]
I've added a version for i24's vertical gonio as well, not sure if that is automatically added to this pull request.

**Comment by ndg63276** [comment]
Bump.

**Comment by thomascobb** [comment]
The first commit looks fine. The second commit looks very similar to `adPythonMxSampleDetect.py`. Is there any way the two can share code?

**Comment by ndg63276** [comment]
Probably, although the GUI elements only have left-to-right or right-to-left options for the direction. But perhaps that should be a separate PR?

**Comment by ndg63276** [comment]
Second commit removed :)

**Pull request merged**
